### ISSUE TITLE
Upload Wireframes

### ISSUE THREAD

**Issue by jessibcoden** [nss-evening-cohort-06/company-x-whoami#33]

**Comment by alexsanchez728** [comment]
![](https://files.slack.com/files-pri/T03F2SDTJ-F6JPTR6U8/c25ca10a-5e9e-408b-beb4-490b732300b6.jpg)

**Comment by alexsanchez728** [comment]
![c25ca10a-5e9e-408b-beb4-490b732300b6](https://user-images.githubusercontent.com/30006994/29100331-8a375518-7c70-11e7-9867-9f5a2c6fb9df.JPG)
